# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f1681559f943fe4e3619d99a8b206c3"
name = "Ultra Matrix"
application_url = "https://ultra-matrix-production.up.railway.app"
embedded = false
handle = "ultra-matrix-1"

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_content,write_content,read_themes,write_themes,read_products,write_products"

[auth]
redirect_urls = [ "https://ultra-matrix-production.up.railway.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
